apiVersion: apps/v1
kind: Deployment
metadata:
  name: user03-gateway
  namespace: onedayclass
  labels:
    app: user03-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user03-gateway
  template:
    metadata:
      labels:
        app: user03-gateway
    spec:
      containers:
      - name: user03-gateway
        image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user03-gateway:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8080
#          initialDelaySeconds: 10
#          timeoutSeconds: 2
#          periodSeconds: 5
#          failureThreshold: 10
#        livenessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8080
#          initialDelaySeconds: 120
#          timeoutSeconds: 2
#          periodSeconds: 5
#          failureThreshold: 5