apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-gateway
  namespace: onedayclass
  labels:
    app: user-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-gateway
  template:
    metadata:
      labels:
        app: user-gateway
    spec:
      containers:
      - name: user-gateway
        image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$_PROJECT_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5