apiVersion: v1
kind: Service
metadata:
  name: user-gateway
  namespace: onedayclass
  labels:
    app: user-gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-gateway
    type:
      LoadBalancer