apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-viewpage
  namespace: onedayclass
  labels:
    app: user-viewpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-viewpage
  template:
    metadata:
      labels:
        app: user-viewpage
    spec:
      containers:
      - name: user-viewpage
        image: username/viewpage:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        #readinessProbe:
        #  httpGet:
        #    path: '/actuator/health'
        #    port: 8080
        #  initialDelaySeconds: 10
        #  timeoutSeconds: 2
        #  periodSeconds: 5
        #  failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/actuator/health'
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5