apiVersion: apps/v1
kind: Deployment
metadata:
  name: user03-viewpage
  namespace: onedayclass
  labels:
    app: user03-viewpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user03-viewpage
  template:
    metadata:
      labels:
        app: user03-viewpage
    spec:
      containers:
      - name: user03-viewpage
        image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user03-viewpage:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5