apiVersion: apps/v1
kind: Deployment
metadata:
  name: user03-viewpage
  namespace: onedayclass
  labels:
    app: user03-viewpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user03-viewpage
  template:
    metadata:
      labels:
        app: user03-viewpage
    spec:
      containers:
      - name: user03-viewpage
        image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user03-viewpage:v3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "400m"
        readinessProbe:
          httpGet:
            path: '/actuator/health'
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
#        livenessProbe:
#          httpGet:
#            path: '/actuator/health'
#            port: 8080
#          initialDelaySeconds: 120
#          timeoutSeconds: 2
#          periodSeconds: 5
#          failureThreshold: 5