apiVersion: apps/v1
kind: Deployment
metadata:
  name: user03-reservation
  namespace: onedayclass
  labels:
    app: user03-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user03-reservation
  template:
    metadata:
      labels:
        app: user03-reservation
    spec:
      containers:
      - name: user03-reservation
        image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user03-reservation:v1
        ports:
        - containerPort: 8080
        env:
        - name: payurl
          valueFrom:
            configMapKeyRef:
              name: reservation-configmap
              key: payurl 
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
#        readinessProbe:
#          httpGet:
#            path: '/actuator/health'
#            port: 8080
#          initialDelaySeconds: 10
#          timeoutSeconds: 2
#          periodSeconds: 5
#          failureThreshold: 10
#        livenessProbe:
#          httpGet:
#            path: '/actuator/health'
#            port: 8080
#          initialDelaySeconds: 120
#          timeoutSeconds: 2
#          periodSeconds: 5
#          failureThreshold: 5