apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-rev
  namespace: onedayclass
spec:
  hosts:
  - "user03-reservation"
  http:
  - route:
    - destination:
        host: "user03-reservation"
    timeout: 0.1s